name: quiz_buzzer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - pip:
      - bidict==0.23.1
      - blinker==1.6.2
      - cffi==1.17.1
      - click==8.1.7
      - cryptography==45.0.5
      - dnspython==2.7.0
      - et-xmlfile==1.1.0
      - eventlet==0.33.3
      - flask==2.3.3
      - flask-cors==6.0.1
      - flask-socketio==5.3.6
      - greenlet==3.2.3
      - h11==0.16.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - markupsafe==2.1.3
      - numpy==1.26.4
      - openpyxl==3.1.5
      - pandas==2.2.2
      - pycparser==2.22
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - python-engineio==4.12.2
      - python-socketio==5.8.0
      - pytz==2024.1
      - simple-websocket==1.1.0
      - six==1.16.0
      - tzdata==2023.3
      - werkzeug==3.0.3
      - wsproto==1.2.0