name: Deploy Quiz Buzzer to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Verify files exist
      run: |
        echo "Checking for required files:"
        if [ -f "index.html" ]; then
          echo "✅ index.html found"
          head -5 index.html
        else
          echo "❌ index.html not found"
        fi
        
        if [ -f "among_us.html" ]; then
          echo "✅ among_us.html found"
        else
          echo "❌ among_us.html not found"
        fi
        
        if [ -f ".nojekyll" ]; then
          echo "✅ .nojekyll found"
        else
          echo "❌ .nojekyll not found"
        fi
        
        echo "Files in root directory:"
        ls -la | head -20
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 